### ISSUE TITLE
Update the readme of the project with necessary installation guides and photos

### ISSUE THREAD

**Issue by alvin-dennis** [Namya13Jain/Skill_Shala#1]
I plan to update the project readme with necessary photos of the projects. This is because clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started.  Pls assign me this issue under PHICSIT @Namya13Jain

**Comment by Namya13Jain** [comment]
@alvin-dennis assigned this issue to you.

Happy contribution !!
