### ISSUE TITLE
Issue: There should be demo or view link of the platform and the given website link is not the right link.

### ISSUE THREAD

**Issue by Akanksha10029** [Namya13Jain/Skill_Shala#3]
In "Demo of the Application The demo of the website can be found here" section there should be demo or view link and the link that you have given is not the actual website link as it is taking me on the file section again so anyone who wants to go the website, they would not be able to visit the site directly.

**Comment by alvin-dennis** [comment]
@Akanksha10029 thats because its not hosted
i just gave an empty redirect

**Comment by Akanksha10029** [comment]
Ok
